// Place in Assets/single_agent_test/Editor/AmbientFillCSVGenerator.cs

using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;

public class AmbientFillCSVGenerator : EditorWindow
{
    private string outputPath       = "Assets/single_agent_test/ambient_particles/emitter_config.csv";
    private int    particlesPerRoom = 200;
    private float  tau              = 0.1f;
    private float  particleSizeUm   = 1.0f;

    [Tooltip("Fixed half-extents to assign each room (meters). " +
             "Adjust until fill volumes look right in the scene.")]
    private float roomHalfX = 3.0f;
    private float roomHalfY = 1.35f; // half of ~2.7m ceiling height
    private float roomHalfZ = 3.0f;

    private bool   debugMode = false;
    private Vector2 _scroll;
    private string  _lastResult = "";

    [MenuItem("Tools/Generate Ambient Fill CSV")]
    public static void ShowWindow()
        => GetWindow<AmbientFillCSVGenerator>("Ambient Fill CSV Generator");

    void OnGUI()
    {
        _scroll = EditorGUILayout.BeginScrollView(_scroll);

        GUILayout.Label("Ambient Fill CSV Generator", EditorStyles.boldLabel);
        EditorGUILayout.Space();

        EditorGUILayout.HelpBox(
            "Uses each RoomScript's Transform.position as the fill zone centre, " +
            "with configurable fixed half-extents. Run in Debug Mode first to " +
            "verify room positions look reasonable.",
            MessageType.Info);

        EditorGUILayout.Space();
        GUILayout.Label("Output", EditorStyles.boldLabel);
        outputPath = EditorGUILayout.TextField("CSV Path", outputPath);

        EditorGUILayout.Space();
        GUILayout.Label("Room fill volume (half-extents per axis)", EditorStyles.boldLabel);
        roomHalfX = EditorGUILayout.FloatField("Half X (m)", roomHalfX);
        roomHalfY = EditorGUILayout.FloatField("Half Y (m) — half ceiling height", roomHalfY);
        roomHalfZ = EditorGUILayout.FloatField("Half Z (m)", roomHalfZ);

        EditorGUILayout.Space();
        GUILayout.Label("Particle settings", EditorStyles.boldLabel);
        particlesPerRoom = EditorGUILayout.IntField("Particles Per Room", particlesPerRoom);
        tau              = EditorGUILayout.FloatField("Tau (s)", tau);
        particleSizeUm   = EditorGUILayout.FloatField("Particle Size (µm)", particleSizeUm);

        EditorGUILayout.Space();
        debugMode = EditorGUILayout.Toggle("Debug Mode (log positions, don't write CSV)", debugMode);

        EditorGUILayout.Space();
        if (GUILayout.Button(debugMode ? "Debug — Log Room Positions" : "Generate CSV", GUILayout.Height(30)))
            GenerateCSV();

        if (!string.IsNullOrEmpty(_lastResult))
        {
            EditorGUILayout.Space();
            EditorGUILayout.HelpBox(_lastResult, MessageType.None);
        }

        EditorGUILayout.EndScrollView();
    }

    void GenerateCSV()
    {
#if UNITY_6000_0_OR_NEWER
        var rooms = FindObjectsByType<RoomScript>(FindObjectsInactive.Exclude, FindObjectsSortMode.None);
#else
        var rooms = FindObjectsOfType<RoomScript>();
#endif

        if (rooms.Length == 0)
        {
            _lastResult = "No GameObjects with RoomScript found in the active scene.";
            Debug.LogWarning("[AmbientFillCSVGenerator] " + _lastResult);
            return;
        }

        Debug.Log($"[AmbientFillCSVGenerator] Found {rooms.Length} rooms. Positions:");

        var sb = new StringBuilder();
        sb.AppendLine("# Auto-generated by AmbientFillCSVGenerator");
        sb.AppendLine("# emitter_id,type,pos_x,pos_y,pos_z,ext_x,ext_y,ext_z,count,tau,size_um");
        sb.AppendLine("emitter_id,type,pos_x,pos_y,pos_z,ext_x,ext_y,ext_z,count,tau,size_um");

        int written = 0;

        foreach (var room in rooms)
        {
            // Use Transform.position as zone centre — room GameObjects are logical
            // trigger zones, not geometry containers, so renderer bounds are empty.
            Vector3 pos = room.transform.position;

            // Y centre: room objects sit at floor level; offset up by half ceiling height
            Vector3 centre = new Vector3(pos.x, pos.y + roomHalfY, pos.z);

            string id = room.gameObject.name
                .Replace(" ", "_")
                .Replace("(", "")
                .Replace(")", "")
                .ToLower();

            Debug.Log($"  {id}  pos={pos}  centre={centre}");

            if (!debugMode)
            {
                sb.AppendLine(
                    $"{id},ambient," +
                    $"{centre.x:F3},{centre.y:F3},{centre.z:F3}," +
                    $"{roomHalfX:F3},{roomHalfY:F3},{roomHalfZ:F3}," +
                    $"{particlesPerRoom},{tau:F3},{particleSizeUm:F1}");
            }

            written++;
        }

        if (debugMode)
        {
            _lastResult = $"Debug: found {written} rooms. Check Console for positions.";
            return;
        }

        string dir = Path.GetDirectoryName(outputPath);
        if (!string.IsNullOrEmpty(dir) && !Directory.Exists(dir))
            Directory.CreateDirectory(dir);

        File.WriteAllText(outputPath, sb.ToString());
        AssetDatabase.Refresh();

        _lastResult = $"Done — wrote {written} rooms.\nSaved to: {outputPath}";
        Debug.Log($"[AmbientFillCSVGenerator] {_lastResult}");
    }
}